version: "3.9"
services:
  backend:
    image: "xtiltedboy/shortener-api"
    container_name: shortener-api
    restart: 'unless-stopped'
    pull_policy: build
    build:
      context: "."
    ports:
      - 2000:2000
    volumes:
      - /mnt/datos/shortener-api:/content-api/
